#pragma once

enum MessageType {

	TYPE_REPORT_WORKER_THREAD_LAUNCHED = 3,

	TYPE_CloudGetNumFiles = 11,
	TYPE_CloudRead = 12,
	TYPE_CloudWrite = 13,
	TYPE_GameInfo_IsHardcore = 20,
	TYPE_GameInfo_SetModName = 21,
	TYPE_Stash_Item_BasicInfo = 25,

	TYPE_ERROR_HOOKING_GENERIC = 44,
	TYPE_GameInfo_IsHardcore_via_init = 47,

	TYPE_SUCCESS_HOOKING_GENERIC = 52,

	TYPE_ITEMSEEDDATA_PLAYERID = 74,
	TYPE_ITEMSEEDDATA_PLAYERID_ERR_NOGAME = 62,
	TYPE_ITEMSEEDDATA_PLAYERID_ERR_NOITEM = 63,
	TYPE_GAMEENGINE_UPDATE = 8000,
	TYPE_INJECTION_CANCELLED = 8100,
};
