using System.Collections.Generic;
using System.Linq;

namespace StatTranslator {
    public class EnglishLanguage : ILocalizedLanguage {
        public bool WarnIfMissing => true;

        public EnglishLanguage(Dictionary<string, string> existingTags) {
            foreach (var tag in existingTags.Keys)
                SetTagIfMissing(tag, existingTags[tag]);


            var damageTypes = StatManager.BodyDamageTypes;
            var resistance = GetTag("Resistance");
            var toMaxResistance = GetTag("ResistanceMaxResist");

            foreach (var damageType in damageTypes) {
                var r = DamageTypeTranslation(damageType);
                SetTagIfMissing($"defensive{damageType}", $"{{0}}% {r} {resistance}");
                SetTagIfMissing($"defensive{damageType}Resistance", $"{{0}}% {r} {resistance}");
                SetTagIfMissing($"defensive{damageType}MaxResist", $"{{0}}% {toMaxResistance}{r} {resistance}");
            }
        }

        /// <summary>
        /// Copied from StatManager::DamageTypeTranslation
        /// </summary>
        /// <param name="d"></param>
        /// <returns></returns>
        private string DamageTypeTranslation(string d) {
            d = d.Replace("Modifier", "");

            var localized = GetTag(d);

            if (!string.IsNullOrEmpty(localized)) {
                return localized;
            }

            return d.Replace("Base", "");
        }

        public void SetTagIfMissing(string tag, string value) {
            if (!_stats.ContainsKey(tag))
                _stats[tag] = value;
        }

        public string Export() {
            return string.Join("\r\n",
                _stats
                    .OrderBy(entry => entry.Key)
                    .Select((entry, idx) => $"{entry.Key}={entry.Value.Replace("\n", "\\n")}")
            );
        }

        private readonly Dictionary<string, string> _stats = new Dictionary<string, string> {
            {"tagItemNameOrder", "{%_s0}{%_s1}{%_s2}{%_s3}{%_s4}"},


            // Simply Header stats
            {"offensivePierceRatioMin", "{0}% Armor Piercing"},
            {"defensiveProtection", "{0} Armor"},
            {"defensiveStun", "{0}% Reduced Stun Duration"},
            {"petBurstSpawn", "+{0} Summons to {3}"},
            {"skillChanceWeight", "{0}% Chance to be Used"},
            {"skillProjectileNumber", "{0} Projectile"},
            {"skillCooldownTime", "{0} Seconds Skill Recharge"},
            {"skillManaCost", "{0} Energy Cost"},
            {"skillTargetRadius", "{0} Meter Radius"},
            {"skillActiveDuration", "{0} Second Duration"}, // Skills only

            // Simply Body Stats
            {"weaponDamagePct", "+{0}% Weapon Damage"},

            {"offensivePercentCurrentLifeMin", "{0}% Reduction to Enemy\"s Health"},
            {"characterLife", "+{0} Health"},
            {"characterLifeModifier", "+{0}% Health"},
            {"augmentAllLevel", "+{0} to All Skills"},
            {"characterDefensiveAbility", "+{0} Defensive Ability"},
            {"characterOffensiveAbility", "+{0} Offensive Ability"},
            {"characterDefensiveAbilityModifier", "+{0}% Defensive Ability"},
            {"characterOffensiveAbilityModifier", "+{0}% Offensive Ability"},
            {"augmentMastery1", "+{0} to All Skills in {3}"},
            {"augmentMastery2", "+{0} to All Skills in {3}"},
            {"augmentMastery3", "+{0} to All Skills in {3}"},
            {"augmentMastery4", "+{0} to All Skills in {3}"},
            {"augmentSkill1", "+{0} to {3}"},
            {"augmentSkill2", "+{0} to {3}"},
            {"augmentSkill3", "+{0} to {3}"},
            {"augmentSkill4", "+{0} to {3}"},
            {"augmentSkill1Extras", "Tier {0} {3} skill"},
            {"augmentSkill2Extras", "Tier {0} {3} skill"},
            {"augmentSkill3Extras", "Tier {0} {3} skill"},
            {"augmentSkill4Extras", "Tier {0} {3} skill"},
            {"defensivePetrify", "{0}% Reduced Petrify Duration"},
            {"offensiveCritDamageModifier", "+{0}% Crit Damage"},
            {"characterRunSpeedModifier", "+{0}% Movement Speed"},
            {"characterIncreasedExperience", "+{0}% Experience Gain"},
            {"characterIntelligenceModifier", "+{0}% Spirit"},
            {"skillCooldownReduction", "-{0}% Skill Cooldown Reduction"},
            {"retaliationTotalDamageModifier", "+{0}% Total Retaliation Damage"}, // not caught by the .replace("Modifier") for some reason..
            {"characterAttackSpeedModifier", "+{0}% Attack Speed"},
            {"characterAttackSpeed", "+{0}% Attack Speed"},
            {"offensiveLifeLeechMin", "{0}% of Attack Damage converted to Health"},
            {"characterIntelligence", "+{0} Spirit"},
            {"characterManaRegen", "+{0} Energy Regenerated per second"},
            {"characterManaRegenModifier", "+{0}% Energy Regenerated per second"},
            {"characterLightRadius", "+{0}% Light Radius"},
            {"characterDodgePercent", "+{0}% Chance to Avoid Melee Attacks"},
            {"piercingProjectile", "{0}% Chance to pass through Enemies"},
            {"characterMana", "+{0} Energy"},
            {"characterManaModifier", "+{0}% Energy"},
            {"characterEnergyAbsorptionPercent", "{0}% Energy Absorption From Enemy Spells"},
            {"characterSpellCastSpeedModifier", "+{0}% Casting Speed"},
            {"defensiveReflect", "{0}% Damage Reflected"},
            {"blockRecoveryTime", "{0} second Block Recovery"},
            {"characterLifeRegen", "+{0} Health regenerated per second"},
            {"characterDexterity", "+{0} Cunning"},
            {"characterDexterityModifier", "+{0}% Cunning"},
            {"defensiveTrap", "{0}% Reduced Entrapment Duration"},
            {"characterLifeRegenModifier", "+{0}% Health regenerated per second"},
            {"characterDeflectProjectile", "+{0}% Chance to Avoid Projectiles"},
            {"characterConstitutionModifier", "+{0}% Constitution"},
            {"characterHuntingDexterityReqReduction", "-{0}% Cunning Req. for Ranged Weapons"},
            {"characterStrength", "+{0} Physique"},
            {"characterStrengthModifier", "+{0}% Physique"},
            {"characterTotalSpeedModifier", "+{0}% Total Speed"}, // Deprecated?
            {"skillProjectileSpeedModifier", "+{0}% Increase in Projectile Speed"}, // Deprecated?
            {"defensiveAbsorptionModifier", " Increases Armor Absorption by {0}%"},
            {"defensiveAllMaxResist", "+{0} Maximum All Resistances"},
            {"skillLifeBonus", "{0} Health Restored"},
            {"defensiveFreeze", "{0}% Reduced Freeze Duration"},
            {"skillLifePercent", "{0}% Health Restored"},
            {"defensiveTotalSpeedResistance", "{0}% Slow Resistance"},
            {"defensiveBlockModifier", "Increases Shield Block Chance by {0}%"},
            {"offensiveTauntMin", "Taunt target for {0} Seconds"},
            {"defensiveBlockAmountModifier", "+{0}% Shield Damage Blocked"},
            {"characterDefensiveBlockRecoveryReduction", "+{0}% Shield Recovery Time"},
            {"skillTargetAngle", "{0} Targets in a {1}° Angle"},
            {"offensiveStunMin", "Stun target for {0} Seconds"},
            {"offensiveStunMax", "Stun target for {0}-{1} Seconds"},
            {"offensiveStunChance", "{3}% chance to "},
            {"defensiveProtectionModifier", "Increases Armor by {0}%"},
            {"projectilePiercingChance", "{0}% Chance to pass through Enemies"},
            {"characterGlobalReqReduction", "{0}% Reduction to Attribute Requirements"},
            {"projectileExplosionRadius", "{0} Meter Radius"},
            {"sparkChance", "{0}% Chance of affecting up to {1} targets within {2} Meters"},

            // Skill triggers
            {"cast_@allyonattack", " "},
            {"cast_@allyonlowhealth", " "},
            {"cast_@enemylocationonkill", " "},
            {"cast_@enemyonanyhit", " "},
            {"cast_@enemyonattack", "{0}% Chance on attack"},
            {"cast_@enemyonattackcrit", "{0}% Chance on a critical attack (target enemy)"},
            {"cast_@enemyonblock", "{0}% Chance when blocked"},
            {"cast_@enemyonhitcritical", "{0}% Chance when hit by a critical"},
            {"cast_@enemyonkill", "{0}% Chance on Enemy Death"}, //C
            {"cast_@enemyonmeleehit", "{0}% Chance when hit by a melee attack"},
            {"cast_@enemyonprojectilehit", "{0}% NPSkill Proc"},
            {"cast_@selfonanyhit", "{0}% Chance when hit"}, //C
            {"cast_@selfonattack", "{0}% Chance on attacking"},
            {"cast_@selfonattackcrit", "{0}% Chance on a critical attack"},
            {"cast_@selfonblock", "{0}% Chance when blocking"},
            {"cast_@selfonhitcritica", "{0}% Chance when Hit by a Critical"}, //C
            {"cast_@selfonkill", "{0}% Chance on Enemy Death"}, //C
            {"cast_@selfonlowhealth", "{0}% Chance at 25% health"},
            {"cast_@selfonmeleehit", "{0}% Chance when Hit by Melee Attacks"},
            {"cast_@selfonprojectilehit", "{0}% Chance when Hit by Ranged Attacks"},
            {"cast_@selfat", "{0}% Chance at {1}% Health"},

            // Retaliation
            {"customtag_013_retaliation", "{0}-{1} {3} Retaliation"},
            {"customtag_03_retaliation", "{0} {3} Retaliation"},
            {"customtag_retaliation_delay", " over {4} Seconds"},
            {"customtag_slow_retaliation", "{0}% reduced attack speed for {1}s"},

            // Damage
            {"customtag_damage_chanceof", "{0}% Chance of "},
            {"customtag_damage_123", "{1}-{2} {3} Damage"},
            {"customtag_damage_13", "{1} {3} Damage"},
            {"customtag_damage_13%", "+{1}% {3} Damage"},
            {"customtag_damage_delay", " over {4} Seconds"},
            {"customtag_damage_racial", "+{0}% Damage to {3}"},
            {"customtag_damage_racial02", "+{0}% Damage to {3} & {5}"},
            {"customtag_damage_conversion", "{0}% {3} Damage converted to {5}"},

            // Xpac
            {"customtag_xpac_modif_weaponDamagePct", "{0}% Weapon Damage to {3}"},
            {"customtag_xpac_modif_petLimit", "+{0} to Pet Limit to {3}"},
            {"customtag_xpac_modif_physicalResist", "{0} Reduced target's Physical Resistance to {3}"},
            {"customtag_xpac_modif_physicalResistDuration", "{0} Reduced target's Physical Resistance for {1} Seconds to {3}"},
            {"customtag_xpac_modif_dmgConversionPerc", "100% {5} Damage converted to {6} Damage to {3}"},
            {"customtag_xpac_modif_dmgConversion", "{5} Damage converted to {6} Damage to {3}"},
            {"customtag_xpac_modif_speedModifier", "-{0}% Total Speed to {3}"},
            {"customtag_xpac_modif_characterAttackSpeedModifier", "+{0}% Attack Speed to {3}"},
            {"customtag_xpac_modif_defensiveAbilityDebuff", "{0} Defensive Ability to {3}"},
            {"customtag_xpac_modif_defensiveAbilityBuff", "+{0}% Defensive Ability to {3}"},
            {"customtag_xpac_modif_offensiveAbilityBuff", "+{0}% Offensive Ability to {3}"},
            {"customtag_xpac_modif_offensiveTaunt", "Generate Additional Threat to {3}"},
            {"customtag_xpac_modif_addProjectileX", "{0} Projectiles to {3}"},
            {"customtag_xpac_modif_addProjectile1", "1 Projectile to {3}"},
            {"customtag_xpac_modif_offensiveDamageMinMax", "{0}-{1} {5} Damage to {3}"},
            {"customtag_xpac_modif_offensiveDamageMin", "{0} {5} Damage to {3}"},
            {"customtag_xpac_modif_skillManaCostReduction", "-{0}% Skill Energy Cost to {3}"},
            {"customtag_xpac_modif_skillTargetRadius", "{0} Meter Target Area to {3}"},
            {"customtag_xpac_modif_sparkChance", "{0}% Chance of affecting up to {1} targets to {3}"},
            {"customtag_xpac_modif_skillCooldownTime", "{0} Second Skill Recharge to {3}"},
            {"customtag_xpac_modif_offensiveCritDamageModifier", "+{0}% Crit Damage to {3}"},
            {"customtag_xpac_modif_skillActiveDuration", "{0} Second Duration to {3}"},
            {"customtag_xpac_modif_defense", "{0}% {5} Resistance to {3}"},
            {"customtag_xpac_modif_defensiveAbilityDebuffForDuration", "{1} Reduced target's Defensive Ability for {0} Seconds to {3}"},
            {"customtag_xpac_modif_skillLifePercent", "{0}% Health Restored to {3}"},
            {"customtag_xpac_modif_skillTargetAngle", "{0} Degree Attack Arc to {3}"},
            {"customtag_xpac_modif_skillTargetNumber", "{0} Target Maximum to {3}"},
            {"customtag_xpac_modif_skillCooldownReductionChance", "{0}% Chance of +{1}% Skill Cooldown Reduction to {3}"},
            {"customtag_xpac_modif_offensiveTotalDamageReductionPercentDurationMin", "{0}% Reduced target's Damage for {1} Seconds to {3}"},
            {"customtag_xpac_modif_offensiveTotalResistanceReductionAbsoluteMin", "{0} Reduced target's Resistances for {1} Seconds to {3}"},
            {"customtag_xpac_modif_offensiveDamageMultModifier", "Total Damage Modified by {0}% to {3}"},
            {"customtag_xpac_modif_retaliationTotalDamageModifier", "+{0}% to All Retaliation Damage to {3}"},
            {"offensiveXDurationModifier", "+{1}% {5} Damage with +{0}% Increased Duration to {3}"},

            {"racialBonusPercentDefense", "+{0}% Less Damage From {3}"},
            {"racialBonusPercentDefense02", "+{0}% Less Damage From {3} & {5}"},

            {"customtag_faction_boost", "+{0}% faction gain with {3}"},
            {"User7", "Black Legion"},
            {"User2", "Homestead"},
            {"User4", "Outcast"},
            {"User8", "Kymon's Chosen"},
            {"Survivors", "Devil's Crossing"},
            {"User0", "The Rovers"},
            {"User5", "Order of Death's Vigil"},
            {"Aetherials", "Aetherials"},
            {"Cthonians", "Cthonians"},
            {"Outlaws", "Outlaws"},
            {"User6", "Undead"},

            {"customtag_block_012", "{0}% Chance to Block {1} Damage ({2}% Absorption)"},
            {"customtag_block_01", "{0}% Chance to Block {1} Damage"},
            {"customtag_speed", "Speed: {3} ({0})"},

            {"customtag_resistance_reduction", "{0}% Chance of {1}% Reduced target's Resistance For {2} Seconds"},

            // Races
            {"Race001", "Undead"},
            {"Race002", "Beastkin"},
            {"Race003", "Aetherials"},
            {"Race004", "Chthonic"},
            {"Race005", "Aether Corruption"},
            {"Race009", "Human"},
            {"Race012", "Beastkin"},

            // Attack speeds
            {"tagAttackSpeedVeryFast", "Very Fast"},
            {"tagAttackSpeedFast", "Fast"},
            {"tagAttackSpeedAverage", "Average"},
            {"tagAttackSpeedSlow", "Slow"},
            {"tagAttackSpeedVerySlow", "Very Slow"},

            // Damage types            
            {"SlowPhysical", "Internal Trauma"},
            {"SlowFire", "Burn"},
            {"SlowCold", "Frost"},
            {"SlowLightning", "Electrocute"},
            {"SlowVitality", "Vitality Decay"},
            {"SlowPoison", "Poison"},
            {"SlowLife", "Vitality Decay"},
            {"SlowBleeding", "Bleeding"},
            {"Poison", "Acid"},
            {"BasePoison", "Acid"},
            {"BonusPhysical", "Bonus"},
            {"Life", "Vitality"},
            {"TotalDamage", "to All"},
            {"iatag_ui_physical", "Physical"},
            {"PercentCurrentLife", "Life Reduction"},

            {"Physical", "Physical"},
            {"Fire", "Fire"},
            {"Cold", "Cold"},
            {"Vitality", "Vitality"},
            {"Lightning", "Lightning"},
            {"Chaos", "Chaos"},
            {"Bleeding", "Bleeding"},
            {"Elemental", "Elemental"},
            {"Pierce", "Pierce"},
            {"Aether", "Aether"},

            {"BasePhysical", "Physical"},
            {"BaseFire", "Fire"},
            {"BaseCold", "Cold"},
            {"BaseVitality", "Vitality"},
            {"BaseLightning", "Lightning"},
            {"BaseChaos", "Chaos"},
            {"BaseBleeding", "Bleeding"},
            {"BaseElemental", "Elemental"},
            {"BasePierce", "Pierce"},
            {"BaseAether", "Aether"},
            {"BaseLife", "Vitality"},
            {"Resistance", "Resistance"},
            {"ResistanceMaxResist", "to Maximum "},


            {"iatag_damage_Physical", "Physical"},
            {"iatag_damage_Fire", "Fire"},
            {"iatag_damage_Cold", "Cold"},
            {"iatag_damage_Vitality", "Vitality"},
            {"iatag_damage_Lightning", "Lightning"},
            {"iatag_damage_Chaos", "Chaos"},
            {"iatag_damage_Bleeding", "Bleeding"},
            {"iatag_damage_Elemental", "Elemental"},
            {"iatag_damage_Pierce", "Pierce"},
            {"iatag_damage_Aether", "Aether"},

            // Damage version (ref spanish "el fuego", "al fuego")
            {"iatag_damage_BasePhysical", "Physical"},
            {"iatag_damage_BaseFire", "Fire"},
            {"iatag_damage_BaseCold", "Cold"},
            {"iatag_damage_BaseVitality", "Vitality"},
            {"iatag_damage_BaseLightning", "Lightning"},
            {"iatag_damage_BaseChaos", "Chaos"},
            {"iatag_damage_BaseBleeding", "Bleeding"},
            {"iatag_damage_BaseElemental", "Elemental"},
            {"iatag_damage_BasePierce", "Pierce"},
            {"iatag_damage_BaseAether", "Aether"},
            {"iatag_damage_BaseLife", "Vitality"},
            {"iatag_damage_SlowPhysical", "Internal Trauma"},
            {"iatag_damage_SlowFire", "Burn"},
            {"iatag_damage_SlowCold", "Frost"},
            {"iatag_damage_SlowLightning", "Electrocute"},
            {"iatag_damage_SlowVitality", "Vitality Decay"},
            {"iatag_damage_SlowPoison", "Poison"},
            {"iatag_damage_SlowLife", "Vitality Decay"},
            {"iatag_damage_SlowBleeding", "Bleeding"},
            {"iatag_damage_Poison", "Acid"},
            {"iatag_damage_BasePoison", "Acid"},
            {"iatag_damage_BonusPhysical", "Bonus"},
            {"iatag_damage_Life", "Vitality"},
            {"iatag_damage_TotalDamage", "to All"},
            {"iatag_damage_iatag_ui_physical", "Physical"},
            {"iatag_damage_PercentCurrentLife", "Life Reduction"},

            // HTML
            {"iatag_html_choose_a_relic", "Choose a Relic"},
            {"iatag_html_choose_a_recipe", "Choose a Recipe"},
            {"iatag_html_choose_a_component", "Choose a Component"},
            {"iatag_html_badstate_close", "Close"},
            {"iatag_html_transferall", "Transfer all"},
            {"iatag_html_transfer", "Transfer to Stash"},
            {"iatag_html_transfer_cmp", "Compare & Transfer"},
            {"iatag_html_buddies_tooltip", "One of your buddies has this item"},
            {"iatag_html_items_youcancraftthisitem", "You can craft this item."},
            {"iatag_html_cloud_ok", "This item has been backed up to the cloud"},
            {"iatag_html_cloud_err", "This item has not been backed up to the cloud"},
            {"iatag_html_cloud_ok_hw", "This item has been flown up to the clouds"},
            {"iatag_html_cloud_err_hw", "This item has not been flown up to the clouds"},
            {"iatag_html_cloud_ok_easter", "The easter bunny has safely stored this item away"},
            {"iatag_html_cloud_err_easter", "The easter bunny has not yet found this egg"},
            {"iatag_html_items_buddy_alsohasthisitem1", "«{0}» also has this item"},
            {"iatag_html_items_buddy_alsohasthisitem2", "These buddies also have this item: {0}"},
            {"iatag_html_items_buddy_alsohasthisitem3", "of your Buddies have this item"},
            {"iatag_html_items_buddy_alsohasthisitem4", "«{0}» has this item."},
            {"iatag_html_levlerequirement", "Level Requirement: {0}"},
            {"iatag_html_any", "Any"},
            {"iatag_html_items_affix2", "This item has two green affixes"},
            {"iatag_html_items_affix3", "This item has three green affixes! (Rare!)"},
            {"iatag_html_items_unknown", "Unknown Item"},
            {"iatag_html_bonustopets", "Bonus to All Pets"},
            {"iatag_html_copytoclipboard", "Copy to Clipboard"},
            {"iatag_html_tab_header_items", "Items"},
            {"iatag_html_tab_header_help", "Help"},
            {"iatag_html_tab_header_collections", "Collections"},
            {"iatag_html_tab_header_crafting", "Crafting"},
            {"iatag_html_tab_header_components", "Components"},
            {"iatag_html_tab_header_videoguide", "Video Guide"},
            {"iatag_html_tab_header_videoguide_url", "https://www.twitch.tv/videos/210592694"},
            {"iatag_html_tab_header_discord", "Discord"},
            {"iatag_html_crafting_lacking", "You are currently lacking:"},
            {"iatag_html_items_no_items", "No items found!"},
            {"iatag_html_items_grantsskill", "Grants Skill: "},
            {"iatag_html_items_level", "Level {0}"},
            {"iatag_html_badstate_title", "Ooops!"},
            {"iatag_html_badstate_subtitle", "It seems IA has gotten in a bad state!"},
            {"iatag_html_onlinesync_ok", "This item has been backed up to the cloud"},
            {"iatag_html_onlinesync_err", "This item has not been backed up to the cloud"},
            {"iatag_html_augmentation_item", "You may be able to purchase this augment from {0}"},
            {"iatag_html_setbonus", "Set:"},
            {"iatag_html_nomoreitems", "No more items"},
            {"iatag_html_setconsistsof", "This set consists of the following items: "},
            {"iatag_html_displaying", "Displaying {0}"},
            {"iatag_html_filter_owned", "Owned only"},
            {"iatag_html_filter_missing", "Missing only"},
            {"iatag_html_h2", "Experimental feature"},
            {"iatag_html_ingress1", "This feature was added as Proof-of-concept at request from a user."},
            {"iatag_html_ingress2", "It may get improved or removed in the future, depending on usage."},
            {"iatag_html_clearall", "Clear all"},
            {"iatag_html_genericstats", "Generic Stats"},
            {"iatag_html_buddies_watermark", "Buddyitem"},

            {"iatag_ui_orderbylevel_tooltip", "If items should be ordered by level, instead of alphabetically."},
            {"iatag_ui_level_requirement_tooltip", "Level requirements for the item"},
            {"iatag_ui_searchbox_tooltip", "The item name, partially works fine."},
            {"iatag_ui_itemquality_tooltip", "The minimum item quality"},
            {"iatag_ui_slotfilter_tooltip", "Slot/Type"},
            {"iatag_ui_modfilter_tooltip", "Mod / Hardcore / Vanilla"},
            {"iatag_ui_minlevel_tooltip", "The minimum level required to use this item"},
            {"iatag_ui_maxlevel_tooltip", "The maximum level required to use this item"},
            {"iatag_ui_exportsuccess", "Items exported!"},
            {"iatag_ui_cloudsync_mb", "Ooops!\nIt seems you are synchronizing your saves to steam cloud..\nThis tool is unfortunately not compatible.\n"},
            {"iatag_ui_corrupted", "Game installation is corrupted.\nPlease verify the integrity of your Grim Dawn installation and try again.\n\n(Easily done in steam)"},
            {"iatag_ui_update_header", "Check for updates"},
            {"iatag_ui_update_body", "Checking for updates.. if there is a new version, the update dialogue will appear.."},
            {"iatag_ui_checkforupdates", "Check for updates"},
            {"iatag_ui_itemassistant", "Item Assistant"},
            {"iatag_ui_howtorestore", "How do I restore backups?"},
            {"iatag_ui_updatingstats_title", "Updating stats for owned items.."},
            {"iatag_ui_updatingstats", "Updating stats for your items..."},
            {"iatag_ui_darkmode", "Dark mode"},
            {"iatag_ui_autodismiss", "Auto dismiss notifications"},
            {"iatag_ui_nagscreen1_button", "Maybe later..."},
            {"iatag_ui_nagscreen2_button", "Hah, as if!"},
            {"iatag_ui_nagscreen3_button", "Never! Muhaha!"},
            {"iatag_ui_nagscreen4_button", "Why would I?"},
            {"iatag_ui_nagscreen5_button", "Stop nagging me!"},
            {"iatag_ui_nagscreen_title", "Would you like to donate to the developer of Item Assistant?"},
            {"iatag_ui_nagscreen_header", "IA : Would you like to donate?"},

            {"iatag_ui_db_invalidlocation_body", "This folder does not contain an installation of Grim Dawn"},
            {"iatag_ui_db_invalidlocation_title", "Invalid folder"},
            {"iatag_ui_manual_db", "Configure"},
            {"iatag_ui_clean", "Clean Database"},
            {"iatag_ui_buddy_userid", "User ID: "},
            {"iatag_ui_buddy_userid_none", "None"},
            {"iatag_ui_buddy_userid_name", "Name: "},
            {"iatag_ui_buddy_userid_numeric_error_message", "Six digit number, ask your buddy for his id"},
            {"iatag_ui_buddy_userid_doesnotexist_error_message", "This user id does not appear to exist"},
            {"iatag_ui_buddy_nickname_error_message", "Please fill in a nickname to recognize this buddy"},
            {"iatag_ui_online_backups_disabled", "Online backups are disabled"},
            {"iatag_ui_online_backup_email", "You are logged in as {OnlineBackupEmail}"},
            {"iatag_ui_buddy_save", "Save"},
            { "iatag_ui_buddy_toggle", "Toggle visibility"},
            {"iatag_ui_buddy_id", "Buddy Id:"},
            {"iatag_ui_buddy_nickname", "Buddy Nickname:"},
            {"iatag_ui_buddy_intro", "Add new buddy"},
            {"iatag_ui_x_items_backed_up", "{numSynchronized}/{numItems} items backed up, {numUnsynchronizedItems} remaining.."},
            {"iatag_ui_all_items_backed_up", "All of your items have been backed up."},
            {"iatag_ui_backup_delete", "Delete backup"},
            {"iatag_ui_hc", " (HC)"},
            {"iatag_ui_vanilla", "No mod"},
            {"iatag_ui_no_fg", "FG Disabled"},
            {"iatag_ui_no_expansion", "AOM/FG disabled"},
            {"iatag_ui_vanilla_xpac", "AoM"},
            {"iatag_ui_forgottengods", "Forgotten Gods"},
            {"iatag_ui_none", "None"},
            {"iatag_ui_yes", "Yes"},
            {"iatag_ui_no", "No"},
            {"iatag_ui_survivalmode", "The Crucible (DLC)"},
            {"iatag_ui_dualcomputer", "Using IA on multiple PCs"},
            {"iatag_ui_deleteduplicates", "Delete bugged duplicates"},
            {"iatag_ui_backup_service_error", "The backup service is currently experiencing technical difficulties.\nPlease try again later."},
            {"iatag_ui_backup_status", "Backup status"},
            {"iatag_ui_backup_complete", "Backup complete!"},
            {"iatag_ui_backup_failed", "Backup failed, see the log file for more detailed information."},
            {"iatag_ui_backup_details", "Details"},
            {"iatag_ui_backup_logout", "Logout"},
            {"iatag_ui_backup_status_label", "Status:"},
            {"iatag_ui_backup_logout_successful_body", "You have been signed out of online backups\n\nGood luck!"},
            {"iatag_ui_backup_logout_successful_header", "Online backups disabled"},
            {"iatag_ui_backup_deleteaccount_header", "Delete online backups"},
            {"iatag_ui_backup_deleteaccount_body", "Are you sure you wish to delete your online backups?"},
            {"iatag_ui_backup_deleteaccount_success_header", "Online backups deleted"},
            {"iatag_ui_backup_deleteaccount_success_body", "Your online backups has been deleted"},
            {"iatag_ui_backup_deleteaccount_failure_header", "An error has occurred"},
            {"iatag_ui_backup_deleteaccount_failure_body", "An error has occurred while deleting the online backups, please try again later."},
            {"iatag_ui_load_database", "Load Database"},
            {"iatag_ui_backup_loggedinas", "Logged in as {0}"},
            {"iatag_ui_backup_statusunknown", "Unknown/Error"},
            {"iatag_ui_backup_notloggedin", "Not logged in"},
            {"iatag_ui_update_item_stats", "Update Item Stats"},
            {"iatag_ui_open_logfile", "Open the full log file"},
            {"iatag_ui_help", "Discord / Help"},
            {"iatag_ui_source_code", "Source code"},
            {"iatag_ui_online_backup", "Cloud Backup"},
            {"iatag_ui_language_select", "Language Select"},
            {"iatag_ui_backup_viewcharacters", "View Characters"},
            {"iatag_ui_change_language", "Change Language"},
            {"iatag_ui_language_selection", "Language Selection"},
            {"iatag_ui_language_by_author", "{0} by {1}"},
            {"iatag_ui_classes", "Classes"},
            {"iatag_ui_tab_items", "Items"},
            {"iatag_ui_devtools", "Devtools"},
            {"iatag_ui_lootmanually", "Loot Manually"},
            {"iatag_ui_misc", "Misc"},
            {"iatag_ui_socketedonly", "Has components"},
            {"iatag_ui_duplicatesonly", "Duplicates Only"},
            {"iatag_ui_reflect", "Reflect"},
            {"iatag_ui_block", "Block"},
            {"iatag_ui_setbonus", "Set Bonus"},
            {"iatag_ui_petbonuses", "Pet Bonuses"},
            {"iatag_ui_mastery", "Mastery Skills"},
            {"iatag_ui_castspeed", "Cast Speed"},
            {"iatag_ui_attackspeed", "Attack Speed"},
            {"iatag_ui_health", "Health"},
            {"iatag_ui_offensive", "Offensive"},
            {"iatag_ui_runspeed", "Movement Speed"},
            {"iatag_ui_defensive", "Defensive"},
            {"iatag_ui_experience", "Experience"},
            {"iatag_ui_resistances", "Resistances"},
            {"iatag_ui_resistance_bleeding", "Bleeding"},
            {"iatag_ui_resistance_elemental", "Elemental"},
            {"iatag_ui_resistance_fire", "Fire"},
            {"iatag_ui_resistance_piercing", "Piercing"},
            {"iatag_ui_resistance_physical", "Physical"},
            {"iatag_ui_resistance_poison", "Poison"},
            {"iatag_ui_resistance_cold", "Cold"},
            {"iatag_ui_resistance_chaos", "Chaos"},
            {"iatag_ui_resistance_lightning", "Lightning"},
            {"iatag_ui_resistance_vitality", "Vitality"},
            {"iatag_ui_resistance_aether", "Aether"},
            {"iatag_ui_resistance_stun", "Stun"},

            {"iatag_ui_dot", "Damage over Time"},
            {"iatag_ui_lifeleech", "Life Leech"},
            {"iatag_ui_decay", "Decay"},
            {"iatag_ui_frost", "Frost/freeze"},
            {"iatag_ui_trauma", "Trauma"},
            {"iatag_ui_burn", "Burn"},
            {"iatag_ui_electrocute", "Electrocute"},
            {"iatag_ui_bleeding", "Bleeding"},
            {"iatag_ui_damage", "Damage"},
            {"iatag_ui_totaldmg", "Total Damage"},
            {"iatag_ui_retaliation", "Retaliation"},
            {"iatag_ui_elemental", "Elemental"},
            {"iatag_ui_piercing", "Piercing"},
            {"iatag_ui_fire", "Fire"},
            {"iatag_ui_aether", "Aether"},
            {"iatag_ui_cold", "Cold"},
            {"iatag_ui_acid", "Acid"},
            {"iatag_ui_poison", "Poison"},
            {"iatag_ui_lightning", "Lightning"},
            {"iatag_ui_vitality", "Vitality"},
            {"iatag_ui_chaos", "Chaos"},
            {"iatag_ui_orderbylevel", "Order By Level"},
            {"iatag_ui_tab_settings", "Settings"},
            {"iatag_ui_settings_title", "Settings"},
            {"iatag_ui_showaugments", "Show augments as Items"},
            {"iatag_ui_hideskills", "Hide Skills"},
            {"iatag_ui_autoselectmod", "Auto Select Mod"},
            {"iatag_ui_autosearch", "Auto Search"},
            {"iatag_ui_transferanymod", "Transfer to any mod"},
            {"iatag_ui_showrecipesasitems", "Show recipes as items"},
            {"iatag_ui_securetransfers", "Secure Transfers"},
            {"iatag_ui_mergeduplicates", "Merge Duplicates"},
            {"iatag_ui_minimizetotray", "Minimize to Tray"},
            {"iatag_ui_startminimized", "Start minimized"},
            {"iatag_ui_update_title", "Automatic Updates"},
            {"iatag_ui_experimentalupdates", "Frequent Features"},
            {"iatag_ui_regularupdates", "Regular Updates"},
            {"iatag_ui_misc_title", "Misc"},
            {"iatag_ui_donatenow", "Donate Now!"},
            {"iatag_ui_openforum", "Open Forum"},
            {"iatag_ui_contactdev", "Contact Developer"},
            {"iatag_ui_actions_title", "Actions"},
            {"iatag_ui_advancedsettings", "Advanced"},
            {"iatag_ui_importexport", "Import/Export"},
            {"iatag_ui_viewbackups", "View Backups"},
            {"iatag_ui_viewlogs", "View Logs"},
            {"iatag_ui_tab_mods", "Grim Dawn"},
            {"iatag_ui_tab_online", "Online"},
            {"iatag_ui_mods_header", "Grim Dawn Database"},
            {"iatag_ui_mod_database_mods_header", "Mod"},
            {"iatag_ui_mod_path", "Path"},
            {"iatag_ui_tab_backups", "Backups"},
            {"iatag_ui_login", "Login"},
            {"iatag_ui_backup_location", "Local Backup"},
            {"iatag_ui_backupnow", "Backup Now"},
            {"iatag_ui_custom", "Custom"},
            {"iatag_ui_tab_buddy", "Buddy"},
            {"iatag_ui_buddies", "Buddies"},
            {"iatag_ui_backup_buddy_id", "BuddyId:"},
            {"iatag_ui_buddy_descriptive_help_text", "Buddy items lets you see which items your friends have."},
            {"iatag_ui_buddy_add", "Add buddy"},
            {"iatag_ui_buddy_modify", "Modify buddy"},
            {"iatag_ui_buddy_delete", "Delete buddy"},
            {"iatag_ui_buddy_header_buddy", "Buddy"},
            {"iatag_ui_buddy_header_items", "Items"},
            {"iatag_ui_buddy_header_isvisible", "Visible / Active"},
            {"iatag_ui_buddy_column_visible", "Visible"},
            {"iatag_ui_buddy_column_hidden", "Hidden"},
            {"iatag_ui_configuration", "Configuration"},
            {"iatag_ui_syncnow", "Sync Now"},
            {"iatag_ui_enabled", "Enabled"},
            {"iatag_ui_tab_log", "Log"},
            {"iatag_ui_tab_help", "Help"},
            {"iatag_ui_parsing_gd_resources", "Parsing Grim Dawn resources..."},
            {"iatag_ui_saving_special_stats", "Saving special stats"},
            {"iatag_ui_skills_sanity", "Skills sanity check"},
            {"iatag_ui_mapping_item_names", "Mapping item names"},
            {"iatag_ui_generating_skills", "Generating skills"},
            {"iatag_ui_saving_items", "Saving items"},
            {"iatag_ui_preparing_pet_stats", "Preparing pet stats"},
            {"iatag_ui_loading_tags", "Loading tags"},
            {"iatag_ui_saving_tags", "Saving tags"},
            {"iatag_ui_loading_items", "Loading Items"},
            {"iatag_ui_generating_special_stats", "Generating special stats"},
            {"iatag_ui_language_change_warning", "WARNING: Some controls might not appear correctly upon changing the display language. It is suggested to close and reopen GDIA."},
            {"iatag_ui_level_requirement", "Level"},

            {"iatag_ui_javascript_not_ready_title", "Loading.."},
            {"iatag_ui_javascript_not_ready_body", "IA is still loading resources, please try again in a few moments.."},

            //Classes
            {"iatag_ui_soldier", "Soldier"},
            {"iatag_ui_demolitionist", "Demolitionist"},
            {"iatag_ui_occultist", "Occultist"},
            {"iatag_ui_nightblade", "Nightblade"},
            {"iatag_ui_arcanist", "Arcanist"},
            {"iatag_ui_shaman", "Shaman"},
            {"iatag_ui_inquisitor", "Inquisitor"},
            {"iatag_ui_necromancer", "Necromancer"},
            {"iatag_ui_oathkeeper", "Oathkeeper"},

            {"class00", "abcccc"},
            {"class01", "Soldier"},
            {"class02", "Demolitionist"},
            {"class03", "Occultist"},
            {"class04", "Nightblade"},
            {"class05", "Arcanist"},
            {"class06", "Shaman"},
            {"class07", "Inquisitor"},
            {"class08", "Necromancer"},
            {"class09", "Oathkeeper"},

            {"iatag_ui_questionmark", " ? "},
            {"iatag_ui_howdoifindgrimdawn", "How can I find the Grim Dawn install?"},
            {"iatag_ui_whatisthis", "What is this?"},
            {"iatag_ui_backupsdisabled", "Why is this disabled?"},
            {"iatag_ui_missing_stash_tabs", "Why are these disabled?"},
            {"iatag_ui_why_showing_stashpicker", "Why do I need to choose?"},
            {"iatag_no_stash_abort", "No stash chosen. Aborting transfer."},
            {"iatag_stash_status_error", "Could not inject into Grim Dawn, are you sure the bank is CLOSED?"},
            {"iatag_ui_recentonly", "Recent Only"},
            {"iatag_ui_grants_skill", "Grants Skill"},
            {"iatag_ui_grants_summon_skill", "Grants Summon Skill"},
            {"iatag_ui_energy_regen", "Energy Regeneration"},
            {"iatag_ui_weapon_life_leech", "Weapon Life Leech"},
            {"iatag_ui_weapon_damage_conversion", "Damage Conversion"},
            {"iatag_ui_armorincrease", "Armor increase"},
            {"iatag_ui_cooldown_reduction", "Cooldown Reduction"},
            {"iatag_stash3_failure", "Cannot deposit item, please ensure SHARED Stash tab is empty."},
            {"iatag_stash3_success", "Successfully deposited {0} items"},
            {"iatag_deposit_stash_open", "Cannot deposit item, please close your stash in-game"},
            {"iatag_deposit_stash_full", "Could not insert item, stash full"},
            {"iatag_deposit_stash_sorted", "Cannot deposit item, please open or close your stash in-game (stash was sorted)"},
            {"iatag_deposit_stash_unknown_tooltip", "Stash status is unknown, open & close stash in-game to resolve."},
            {"iatag_deposit_stash_unknown_feedback", "Cannot deposit item, please open and close your stash in-game"},
            {"iatag_deposit_pipe_success", "Item sent to GD"},
            {"iatag_file_does_not_exist", "The specified file does not exist"},
            {"iatag_file_not_zip", "Specified file is not a zip file!?"},
            {"iatag_pg_restore_error", "Error restoring from backup, see log file for more details"},
            {"iatag_stash_open", "Stash: Open"},
            {"iatag_stash_crafting", "Stash: Crafting"},
            {"iatag_stash_closed", "Stash: Closed"},
            {"iatag_stash_error", "Stash: ERROR"},
            {"iatag_stash_unknown", "Stash: Unknown"},
            {"iatag_stash_sorted", "Stash: Open/Restricted"},
            {"iatag_stash_", "Stash: "},
            {"iatag_copied_clipboard", "Items copied to clipboard"},
            {"iatag_stash_not_found", "Could not locate and stash files."},
            {"iatag_legacy_backup", "Invalid backup file. If this is a really old backup, please see the instructions on restoring from a legacy backup."},
            {"iatag_postgres_backup", "Invalid backup file. This backup format has been deprecated. Contact me on itemassistant@gmail.com and I'll send you a manual restore."},
            {"iatag_looted_from_stash", "Looted {0} items from stash {1}"},
            {"iatag_purchase_stash", "Please purchase more stash pages!"},
            {"iatag_invalid_deposit_stash_number", "You have configured IA to deposit to stash {0} but you only have {1} pages"},
            {"iatag_invalid_loot_stash_number", "You have configured IA to loot from stash {0} but you only have {1} pages"},
            {"iatag_stash_might_be_full", "Some items not deposited, stash {0} might be full."},
            {"iatag_not_enough_stash", "Transfer Stash only contains {0} pages. IA requires at least 2 pages to function properly."},
            {"iatag_no_matching_items_found", "No matching items found"},
            {"iatag_items_found_selfonly", "{0} matching items found"},
            {"iatag_items_found_self_and_buddy", "{0} matching items found (with an additional {1} from your friends)"},

            {"iatag_not_implemented", "Functionality not implemented"},

            {"iatag_rarity_any", "Any"},
            {"iatag_rarity_yellow", "Yellow"},
            {"iatag_rarity_green", "Green"},
            {"iatag_rarity_green_p1", "Green (+1)"},
            {"iatag_rarity_green_p2", "Green (+2)"},
            {"iatag_rarity_blue", "Blue"},
            {"iatag_rarity_epic", "Epic"},
            {"TagQualityOld", "Obsolete"},

            {"iatag_feedback_already_logged_in", "You are already logged in"},
            {"iatag_feedback_too_close_to_stash", "Delaying stash loot - Standing too close to stash!"},
            {"iatag_feedback_stash_position_unknown", "Cannot loot, stash position still unknown.."},
            {"iatag_feedback_delaying_stash_loot_status", "Waiting for stash to close.."},
            {"iatag_feedback_no_items_to_loot", "No items to loot in SHARED stash tab"},
            {"iatag_feedback_unable_to_loot_stash", "Unable to loot SHARED stash page."},
            {"iatag_feedback_item_does_not_exist", "Cannot deposit item, item does not appear to exist.. (ghost item)"},
            {"iatag_feedback_cloud_save_enabled_ingame", "WARNING - Grim Dawn Cloud saving is active."},
            {"iatag_feedback_stacked_not_looted", "{0} items were not looted due to being stackable"},
            {"iatag_feedback_unknown_not_looted", "{0} items were not looted due to being unidentified"},
            {"iatag_feedback_duplicates_not_looted", "{0} items were not looted due to being possible duplicates (bugged items)"},
            {"iatag_feedback_unable_to_deposit", "An error occurred depositing items, check the logs."},

            {"iatag_slot_any", "Any"},
            {"iatag_slot_armor", "Armor"},
            {"iatag_slot_head", "Head"},
            {"iatag_slot_hands", "Hands"},
            {"iatag_slot_feet", "Feet"},
            {"iatag_slot_legs", "Legs"},
            {"iatag_slot_chest", "Chest"},
            {"iatag_slot_belt", "Belt"},
            {"iatag_slot_medal", "Medal"},
            {"iatag_slot_ring", "Ring"},
            {"iatag_slot_shoulder", "Shoulder"},
            {"iatag_slot_neck", "Amulet/Neck"},
            {"iatag_slot_weapon1h", "Weapon (1h)"},
            {"iatag_slot_weapon2h", "Weapon (2h)"},
            {"iatag_slot_weaponranged1h", "Weapon (Ranged 1h)"},
            {"iatag_slot_weaponranged2h", "Weapon (Ranged 2h)"},
            {"iatag_slot_offhand", "Offhand"},
            {"iatag_slot_shield", "Shield"},
            {"iatag_slot_component", "Component"},
            {"iatag_slot_relic", "Relic"},
            {"iatag_slot_other", "Other"},

            {"iatag_slot_dagger1h", "Dagger (1h)"},
            {"iatag_slot_mace1h", "Mace (1h)"},
            {"iatag_slot_axe1h", "Axe (1h)"},
            {"iatag_slot_scepter1h", "Scepter (1h)"},
            {"iatag_slot_sword1h", "Sword (1h)"},
            {"iatag_slot_sword2h", "Sword (2h)"},
            {"iatag_slot_mace2h", "Mace (2h)"},
            {"iatag_slot_axe2h", "Axe (2h)"},
            {"iatag_slot_ranged1h", "Ranged (1h)"},
            {"iatag_slot_ranged2h", "Ranged (2h)"},
            {"iatag_slot_scroll", "Scroll"},
            {"iatag_slot_augmentation", "Augmentation"},

            {"tagFactionUser9_ia", "The Outcast"},
            {"tagFactionUser10_ia", "Barrowholm"},
            {"tagFactionUser11_ia", "Malmouth Resistance"},
            {"iatag_ui_dontwantbackups", "I don't want online features, stop asking me!"},
            {"iatag_ui_clean_body", "The internal IA cache has been deleted.\nYour items are still fine, but will shown up as 'Unknown Item'.\n\nIn order to display items, re-parse the GD database."},
            {"iatag_ui_clean_caption", "Cache wiped"},
            {"iatag_ui_tab_secondtolast", "Second to last tab"},
            {"iatag_ui_tab_1", "Tab 1"},
            {"iatag_ui_tab_2", "Tab 2"},
            {"iatag_ui_tab_3", "Tab 3"},
            {"iatag_ui_tab_4", "Tab 4"},
            {"iatag_ui_tab_5", "Tab 5"},
            {"iatag_ui_tab_6", "Tab 6"},
            {"iatag_ui_tab_7", "Tab 7"},
            {"iatag_ui_tab_8", "Tab 8"},
            {"iatag_ui_tab_9", "Tab 9"},
            {"iatag_ui_tab_10", "Tab 10"},
            {"iatag_ui_tab_11", "Tab 11"},
            {"iatag_ui_swapstashwarning", "Changes to \"Loot items from\" may require restarting Grim Dawn"},
            {"iatag_ui_group_move_items_to", "Move items to"},
            {"iatag_ui_tab_lasttab", "Last tab"},
            {"iatag_ui_group_loot_items_from", "Loot items from"},
            {"iatag_ui_button_close", "Close"},
            {"iatag_ui_export", "Export"},
            {"iatag_ui_import", "Import"},
            {"iatag_ui_export_export", "Export"},
            {"iatag_ui_export_stashfile", "Stash File"},
            {"iatag_ui_browse", "Browse.."},
            {"iatag_ui_import_import", "Import"},
            {"iatag_ui_import_stashfile", "Stash File"},
            {"iatag_ui_import_filetype", "File Type"},
            {"iatag_ui_gamestash", "Game Stash"},
            {"iatag_ui_gdstash", "GD Stash"},
            {"iatag_ui_iastash", "IA Stash"},
            {"iatag_ui_translation", "Item Assistant is available in your language! Go to settings and click \"Language\" to change to English."},
            {"iatag_ui_database_modified_body", "The Grim Dawn database appears to have been modified.\nIf there has been a recent patch to Grim Dawn:\nGo to \"Database\\Mods\" and parse the database to discover new items and sets."},
            {"iatag_ui_database_modified_title", "New patch?"},
            // These cannot currently be translated.
            // Once the injection code is moved back into the "core" IA, this should be possible.
            {"iatag_ui_avasted", "Avasted!"},
            {"iatag_ui_avast1", "It appears that one or several essential components of Grim Dawn Item Assistant has been deleted."},
            {"iatag_ui_avast2", "This is typically caused by Avast \"anti virus\" flagging Item Assistant as a false positive, without informing the user."},
            {"iatag_ui_avast3", "In order to keep using IA, you must first whitelist it in whichever anti virus/similar software, and then reinstall IA to restore the missing files.!"},
            {"iatag_ui_avast_ok", "OK"},
            {"iatag_ui_avastlink", "Click here for more information"},

            {"iatag_ui_copiedclipboard", "Copied to clipboard"},
            {"iatag_ui_importexport_nothinginzip_body", "This zip file does not contain any .ias backup files"},
            {"iatag_ui_importexport_nothinginzip_title", "Error"},
            {"iatag_ui_importexport_import_success", "Items imported!"},
            {"iatag_ui_importexport_import_success_body", "Items imported\nIf you already had items, you may have gotten duplicates."},
            {"iatag_ui_importexport_selectfile", "Select the file to import"},
            {"iatag_ui_settings_securetransferdsable_body", "Are you sure you wish to disable secure transfers?\n\nIt will be YOUR responsibility to make sure the bank is closed when transferring."},
            {"iatag_ui_settings_securetransferdsable_title", "Are you sure?"},
            {"iatag_ui_opencustombackup", "Open folder"}
        };

        private const string English = "{%_s0}{%_s1}{%_s2}{%_s3}{%_s4}";
        private readonly ItemNameCombinator _itemCombinator = new ItemNameCombinator(English);

        public string TranslateName(string prefix, string quality, string style, string name, string suffix) {
            return _itemCombinator.TranslateName(prefix, quality, style, name, suffix);
        }

        public string[] Serialize() {
            return _stats.Keys.ToArray();
        }

        public string GetTag(string tag) {
            return _stats.ContainsKey(tag)
                ? _stats[tag]
                : string.Empty;
        }

        public string GetTag(string tag, object[] args) {
            return args.Select((t, i) => i)
                .Aggregate(GetTag(tag), (current, index) => current.Replace($"{{{index}}}", args[index]?.ToString()));
        }
    }
}